name = "coloring-pages-image-proxy"
main = "src/index.js"
compatibility_date = "2025-08-13"

# KV Namespace binding for asset mappings (shared with PDF proxy)
[[kv_namespaces]]
binding = "ASSET_MAPPINGS"
id = "8122081381114c80872c143ae13272fe" # Same as PDF proxy for shared mappings

# Routes for image proxy - SEO-optimized patterns for main category images
[[routes]]
pattern = "coloringvault.com/main-category/*"
zone_name = "coloringvault.com"

[[routes]]
pattern = "www.coloringvault.com/main-category/*"
zone_name = "coloringvault.com"

[env.production]
name = "coloring-pages-image-proxy-production"

[env.development]
name = "coloring-pages-image-proxy-dev"