# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish" # UNCOMMENT THIS LINE
baseURL = "https://www.coloringvault.com/"
defaultContentLanguage = "en"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0
# Force rebuild for layout sync

buildDrafts = false
buildFuture = false

enableEmoji = true

googleAnalytics = "G-4Y8FM29L7W"

# googleAnalytics = "G-XXXXXXXXX"

[pagination]
  pagerSize = 100

[permalinks]
  pages = "/:contentbasename/"

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  filename = 'sitemap.xml'

[mediaTypes]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.ImageSitemap]
    mediaType = "application/xml"
    baseName = "image-sitemap"
    isPlainText = false
    notAlternative = true
  [outputFormats.SitemapIndex]
    mediaType = "application/xml"
    baseName = "sitemapindex"
    isPlainText = false
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "ImageSitemap", "SitemapIndex"]
  page = ["HTML"]
  section = ["HTML"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "series"
        weight = 50

    [[related.indices]]
        name = "authors"
        weight = 20

    [[related.indices]]
        name = "date"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 10
