# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = false

# Logo configuration
logo = "images/coloringvault-coloring-pages-logo.png"

enableA11y = false
enableSearch = true
enableCodeCopy = false

replyByEmail = false


mainSections = ["animals-coloring-pages", "cartoons-coloring-pages", "education-coloring-pages", "fantasy-coloring-pages", "flowers-coloring-pages", "food-coloring-pages", "holidays-coloring-pages", "monthly-coloring-pages", "nature-coloring-pages", "superheroes-coloring-pages", "vehicles-coloring-pages", "video-games-coloring-pages"]
# robots = ""

# Schema.org JSON-LD Debug Mode (set to true to see schema output on pages)
debugSchema = false

# Author Information for Schema.org
[author]
  name = "Ida Lund"
  description = "Professional illustrator and coloring book artist creating beautiful, educational coloring pages for children and adults."
  image = "/images/author.webp"
  url = "/about-the-author"
  jobTitle = "Illustrator & Artist"
  # Social profiles (optional)
  pinterest = "ColoringVault"
  # instagram = "coloringvault" 
  # facebook = "coloringvault"

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
# backgroundImageWidth = 1200

# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images 
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles
# defaultSocialImage = "/android-chrome-512x512.png" # used as default for social media sharing (Open Graph and Twitter)

# highlightCurrentMenuArea = true
# smartTOC = true
# smartTOCHideUnfocusedChildren = true

fingerprintAlgorithm = "sha512" # Valid values are "sha512" (default), "sha384", "sha256"

giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"

[header]
  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = false

[homepage]
  layout = "card" # valid options: page, profile, hero, card, background, custom
  homepageImage = "/images/homepage-hero-2.webp" # used in: hero, and card
  showRecent = false
  layoutBackgroundBlur = false # only used when layout equals background
  disableHeroImageFilter = false # only used when layout equals hero

[homepage.popularPages]
  enabled = true
  title = "Popular Coloring Pages"
  limit = 8
  fallbackToRecent = true # show recent pages if no popular pages found

[homepage.latestPages]
  enabled = true
  title = "Latest Added Coloring Pages"
  limit = 8

[article]
  showDate = false
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  showAuthorBottom = true
  showHero = false
  # heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = false
  showTableOfContents = false
  # showRelatedContent = false
  # relatedContentLimit = 3
  showTaxonomies = false # use showTaxonomies OR showCategoryOnly, not both
  showCategoryOnly = true # use showTaxonomies OR showCategoryOnly, not both
  showAuthorsBadges = false
  showWordCount = false
  sharingLinks = [ "twitter", "facebook", "pinterest", "email", "whatsapp" ]
  showZenMode = false

[list]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  # websiteid = "ABC12345"
  # domain = "llama.yoursite.com"
  # dataDomains = "yoursite.com,yoursite2.com"
  # scriptName = ""
  # enableTrackEvent = true

[selineAnalytics]
  # token = "XXXXXX"
  # enableTrackEvent = true

[buymeacoffee]
  # identifier = ""
  # globalWidget = true
  # globalWidgetMessage = "Hello"
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  pinterest = "ColoringVault"
  # yandex = ""
  # fediverse = ""

[rssnext]
  # feedId = ""
  # userId = ""

[advertisement]
  # adsense = ""

[cookieConsent]
  enabled = true
  storageKey = "coloringvault-cookie-consent"
  expirationDays = 365
  googleAnalyticsId = "G-XXXXXXXXXX"  # Replace with your GA4 ID
  
[cookieConsent.text]
  message = "We respect your privacy and use cookies to improve your experience, analyze traffic, and personalize content."
  acceptAll = "Accept All"
  customize = "Customize"
  reject = "Reject All"
  modalTitle = "Cookie Preferences"
  modalDescription = "We use cookies to enhance your browsing experience and analyze our traffic. You can choose which categories of cookies you allow."
  savePreferences = "Save Preferences"
  showMore = "Show Details"
  showLess = "Hide Details"

# Cookie Categories with detailed information
[cookieConsent.categories.necessary]
  name = "Necessary Cookies"
  description = "Essential for the website to function properly. These cookies enable core functionality and cannot be disabled."
  required = true
  cookies = [
    { name = "Session Cookie", duration = "Session", purpose = "Maintains your session while browsing", provider = "ColoringVault" },
    { name = "Security Cookie", duration = "1 day", purpose = "Protects against cross-site forgery attacks", provider = "ColoringVault" }
  ]

[cookieConsent.categories.functional]
  name = "Functional Cookies"
  description = "Enhance your experience by remembering your preferences and settings."
  required = false
  cookies = [
    { name = "Theme Preference", duration = "1 year", purpose = "Remembers your light/dark mode preference", provider = "ColoringVault" },
    { name = "Language Setting", duration = "1 year", purpose = "Stores your preferred language", provider = "ColoringVault" }
  ]

[cookieConsent.categories.analytics]
  name = "Analytics Cookies"
  description = "Help us understand how visitors interact with our website by collecting anonymous information."
  required = false
  cookies = [
    { name = "Google Analytics", duration = "2 years", purpose = "Tracks page views and user behavior anonymously", provider = "Google LLC" },
    { name = "_ga", duration = "2 years", purpose = "Distinguishes unique users", provider = "Google LLC" },
    { name = "_gid", duration = "1 day", purpose = "Distinguishes unique users", provider = "Google LLC" }
  ]

[cookieConsent.categories.performance]
  name = "Performance Cookies"
  description = "Collect information about how you use our website to help us improve its performance."
  required = false
  cookies = [
    { name = "Page Load Time", duration = "Session", purpose = "Measures page loading speed", provider = "ColoringVault" }
  ]

[cookieConsent.categories.advertising]
  name = "Advertising Cookies"
  description = "Used to make advertising messages more relevant to you and your interests."
  required = false
  cookies = [
    { name = "Ad Targeting", duration = "30 days", purpose = "Shows relevant advertisements", provider = "Third Party" }
  ]
