/**
 * Helper script to upload PDF mappings to Cloudflare KV
 * Run this after fetching content from Sanity
 */

// Example mappings - these will be generated by your build script
const PDF_MAPPINGS = {
  // Slug -> Sanity CDN URL
  "robot-coloring-page": "https://cdn.sanity.io/files/zjqmnotc/production/61a407c3b2962494e800c495f442a743b4bb2e1f.pdf",
  "teddy-bear-at-the-beach": "https://cdn.sanity.io/files/zjqmnotc/production/e015aec60afc0ba948ae9c3855ef6af7fbb2ee79.pdf",
  "teddy-bear-sleeps": "https://cdn.sanity.io/files/zjqmnotc/production/5734c39c3a3d39849cc19534260024e1a9282591.pdf",
  "teddy-bear-singing": "https://cdn.sanity.io/files/zjqmnotc/production/61a407c3b2962494e800c495f442a743b4bb2e1f.pdf",
  "carpenter-workshop-coloring-page": "https://cdn.sanity.io/files/zjqmnotc/production/4b225f724bbcec311db007dd3de8a218d76289ef.pdf",
  "cute-cat-scooter-coloring-page": "https://cdn.sanity.io/files/zjqmnotc/production/8f7756d085f8b2fab5be23547424a6142d04e3c8.pdf",
};

// This will be replaced with actual data from your build process
export default PDF_MAPPINGS;