name = "enhanced-image-proxy"
main = "src/index.js"
compatibility_date = "2024-08-17"

# KV binding for asset mappings
[[kv_namespaces]]
binding = "ASSET_MAPPINGS"
id = "your-kv-namespace-id"  # Replace with your actual KV namespace ID

# Route configuration for enhanced image proxy
[[routes]]
pattern = "www.coloringvault.com/collections/*/*/image.webp*"
zone_name = "coloringvault.com"

[[routes]]
pattern = "www.coloringvault.com/main-category/*/image.webp*"
zone_name = "coloringvault.com"

# Environment variables (if needed)
[vars]
SANITY_PROJECT_ID = "zjqmnotc"
SANITY_DATASET = "production"