import {defineField, defineType} from 'sanity'

export const coloringPage = defineType({
  name: 'coloringPage',
  title: 'Coloring Page',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'hashtags', title: 'Hashtags'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'content',
      options: {
        source: 'title',
        maxLength: 96,
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      group: 'content',
      rows: 2,
    }),
    defineField({
      name: 'image',
      title: 'Coloring Image',
      type: 'image',
      group: 'content',
      options: {hotspot: true},
      validation: (rule) => rule.required(),
      fields: [
        {
          name: 'alt',
          title: 'Alt Text',
          type: 'string',
          description: 'Important for SEO and accessibility',
          validation: (rule) => rule.required(),
        },
      ],
    }),
    defineField({
      name: 'pdfFile',
      title: 'PDF File',
      type: 'file',
      group: 'content',
      description: 'The downloadable PDF for this coloring page',
      options: {
        accept: 'application/pdf',
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'metadata',
      title: 'Filtering Metadata',
      type: 'object',
      group: 'content',
      description: 'Optional - only for items that need filtering (e.g., flags, animals by type)',
      fields: [
        {
          name: 'continent',
          title: 'Continent',
          type: 'string',
          options: {
            list: [
              {title: 'Africa', value: 'africa'},
              {title: 'Asia', value: 'asia'},
              {title: 'Europe', value: 'europe'},
              {title: 'North America', value: 'northAmerica'},
              {title: 'South America', value: 'southAmerica'},
              {title: 'Oceania', value: 'oceania'},
              {title: 'Antarctica', value: 'antarctica'},
            ],
          },
        },
        {
          name: 'country',
          title: 'Country',
          type: 'string',
          description: 'Country name for flags',
        },
        {
          name: 'category',
          title: 'Sub-category',
          type: 'string',
          description: 'For categorizing within a post (e.g., mammals, birds, reptiles)',
        },
        {
          name: 'tags',
          title: 'Tags',
          type: 'array',
          of: [{type: 'string'}],
          options: {
            layout: 'tags',
          },
          description: 'Additional tags for filtering',
        },
      ],
      options: {
        collapsible: true,
        collapsed: true,
      },
    }),
    defineField({
      name: 'hashtagInstagram',
      title: 'Instagram Hashtags',
      type: 'array',
      group: 'hashtags',
      of: [{type: 'string'}],
      options: {
        layout: 'tags',
      },
      description: 'Hashtags specifically for Instagram (without # symbol)',
    }),
    defineField({
      name: 'hashtagPinterest',
      title: 'Pinterest Hashtags',
      type: 'array',
      group: 'hashtags',
      of: [{type: 'string'}],
      options: {
        layout: 'tags',
      },
      description: 'Hashtags specifically for Pinterest (without # symbol)',
    }),
    defineField({
      name: 'pinDescriptionTemplate',
      title: 'Pin Description Template',
      type: 'text',
      group: 'hashtags',
      rows: 3,
      initialValue: 'Check out our {{title}} coloring page from {{category}}! #coloringpage #{{category}}',
      description: 'Template for pin descriptions. Use {{title}}, {{category}}, {{difficulty}} variables',
    }),
    defineField({
      name: 'pinterestImage',
      title: 'Pinterest Image',
      type: 'image',
      group: 'content',
      description: 'Custom image for Pinterest sharing',
      options: {hotspot: true},
    }),
    defineField({
      name: 'instagramImage',
      title: 'Instagram Image',
      type: 'image',
      group: 'content',
      description: 'Custom image for Instagram sharing',
      options: {hotspot: true},
    }),
    defineField({
      name: 'facebookImage',
      title: 'Facebook Image',
      type: 'image',
      group: 'content',
      description: 'Custom image for Facebook sharing',
      options: {hotspot: true},
    }),
    defineField({
      name: 'isPostedToFacebook',
      title: 'Is Posted to Facebook',
      type: 'boolean',
      group: 'content',
      description: 'Toggle to track if this coloring page has been posted to Facebook',
      initialValue: false,
    }),
    defineField({
      name: 'isPostedToInstagram',
      title: 'Is Posted to Instagram',
      type: 'boolean',
      group: 'content',
      description: 'Toggle to track if this coloring page has been posted to Instagram',
      initialValue: false,
    }),
  ],
  preview: {
    select: {
      title: 'title',
      media: 'image',
    },
  },
})