name = "coloring-pages-asset-proxy"
main = "src/index.js"
compatibility_date = "2025-08-13"

# KV Namespace binding for asset mappings (shared with image proxy)
[[kv_namespaces]]
binding = "ASSET_MAPPINGS"
id = "8122081381114c80872c143ae13272fe" # Shared with image proxy

# Routes for asset proxy - handles both PDFs and images
[[routes]]
pattern = "coloringvault.com/pdf/*"
zone_name = "coloringvault.com"

[[routes]]
pattern = "www.coloringvault.com/pdf/*"
zone_name = "coloringvault.com"

[env.production]
name = "coloring-pages-asset-proxy-production"

[env.development]
name = "coloring-pages-asset-proxy-dev"