name = "coloring-pages-pdf-proxy"
main = "src/index.js"
compatibility_date = "2025-08-13"

# KV Namespace binding for PDF mappings
[[kv_namespaces]]
binding = "PDF_MAPPINGS"
id = "8122081381114c80872c143ae13272fe" # Will be replaced after creating namespace

# Routes for PDF proxy - hierarchical only
[[routes]]
pattern = "coloringvault.com/*"
zone_name = "coloringvault.com"

[[routes]]
pattern = "www.coloringvault.com/*"
zone_name = "coloringvault.com"

[env.production]
name = "coloring-pages-pdf-proxy-production"

[env.development]
name = "coloring-pages-pdf-proxy-dev"